### ISSUE TITLE
create_graph.py crashes after some time

### ISSUE THREAD

**Issue by ADetilie** [hovsg/HOV-SG#8]
@abwerby thank you for quick fix! I don't encounter such problems right now.

However, when I am trying to generate scene graph, I repeatedly face crashes:
```bash
(hovsg) ➜  HOV-SG git:(main) ✗ python application/create_graph.py main.dataset=hm3dsem main.dataset_path=data/hm3dsem_walks/val/00824-Dd4bFSTQ8gi/ main.save_path=data/scene_graphs/00824-Dd4bFSTQ8gi
/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.26.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
[2024-07-23 12:37:18,487][root][INFO] - Loaded ViT-H-14 model config.
[2024-07-23 12:37:26,890][root][INFO] - Loading pretrained ViT-H-14 weights (checkpoints/laion2b_s32b_b79k.bin).
Creating RGB-D point cloud: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226/226 [00:26<00:00,  8.58it/s]
Extracting features: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226/226 [20:37<00:00,  5.47s/it]
Merging 3d masks sequentially
  6%|██████████                                                                                                                                                        | 14/225 [25:23<19:20:49, 330.09s/it][1]    100314 killed     python application/create_graph.py main.dataset=hm3dsem  
```

Traces show that some processes were killed on my machine, due to `Out of memory` problem. Despite the machine having 62 gigs of RAM.
![image (5)](https://github.com/user-attachments/assets/8128f88e-0840-44bb-816d-c90493d0cb9f)

What are the memory requirements for this script to run properly?

_Originally posted by @ADetilie in https://github.com/hovsg/HOV-SG/issues/6#issuecomment-2245406682_

**Comment by ADetilie** [comment]
<img width="1792" alt="Screenshot 2024-07-23 at 19 33 42" src="https://github.com/user-attachments/assets/904490bb-594a-45b0-b3b3-316f4d2379bd">

There are RAM usage spikes during script work. This script just ate 120 gig of RAM.
Are there any configurations of the project which allow reduce memory usage?
Or maybe this is some meory leak?

**Comment by abwerby** [comment]
#7 check this issue.

**Comment by ADetilie** [comment]
Thanks. I hadn't Out of memory crash this time, but faced the following exception:

```bash
-- removing small and empty masks --
number of masked pcds:  1202
number of mask_feats:  1202
masked pcds saved to disk in data/scene_graphs_new/00824-Dd4bFSTQ8gi/hm3dsem/00824-Dd4bFSTQ8gi
full pcd saved to disk in data/scene_graphs_new/00824-Dd4bFSTQ8gi/hm3dsem/00824-Dd4bFSTQ8gi
full pcd feats saved to disk in data/scene_graphs_new/00824-Dd4bFSTQ8gi/hm3dsem/00824-Dd4bFSTQ8gi
hm3dsem
segmenting floors...
downpcd (294355, 3)
bins 281.20046911000327
distance 20.0
1047.017793594306
min_peak_height 1490.0
clustred_peaks [0.00603302 2.43776661]
floors [[0.006033019964371361, 2.4377666140473178]]
number of floors:  1
segmenting rooms...
grid_size:  0.05
occupancy_map shape:  (340, 340)
range of dist:  0.0 48.0
Error executing job with overrides: ['main.dataset=hm3dsem', 'main.dataset_path=data/hm3dsem_walks_new/val/00824-Dd4bFSTQ8gi/', 'main.save_path=data/scene_graphs_new/00824-Dd4bFSTQ8gi']
Traceback (most recent call last):
  File "/home/ncdev/repos/HOV-SG/application/create_graph.py", line 34, in main
    hovsg.build_graph(save_path=save_dir)
  File "/home/ncdev/repos/HOV-SG/hovsg/graph/graph.py", line 814, in build_graph
    self.segment_rooms(floor, save_path)
  File "/home/ncdev/repos/HOV-SG/hovsg/graph/graph.py", line 489, in segment_rooms
    room_vertices = distance_transform(full_map, resolution, tmp_floor_path)
  File "/home/ncdev/repos/HOV-SG/hovsg/utils/graph_utils.py", line 236, in distance_transform
    plt.figure()
  File "/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1027, in figure
    manager = new_figure_manager(
  File "/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/matplotlib/pyplot.py", line 550, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
  File "/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 3507, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 3512, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
  File "/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1797, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
  File "/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/matplotlib/backends/_backend_tk.py", line 504, in create_with_canvas
    manager = cls(canvas, num, window)
  File "/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/matplotlib/backends/_backend_tk.py", line 457, in __init__
    super().__init__(canvas, num)
  File "/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2655, in __init__
    self.toolbar = self._toolbar2_class(self.canvas)
  File "/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/matplotlib/backends/_backend_tk.py", line 649, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2850, in __init__
    self._nav_stack = cbook._Stack()
  File "/home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/matplotlib/_api/__init__.py", line 217, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib.cbook' has no attribute '_Stack'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

**Comment by Eku127** [comment]
> ```
>           @abwerby thank you for quick fix! I don't encounter such problems right now.
> ```
> 
> However, when I am trying to generate scene graph, I repeatedly face crashes:
> 
> ```shell
> (hovsg) ➜  HOV-SG git:(main) ✗ python application/create_graph.py main.dataset=hm3dsem main.dataset_path=data/hm3dsem_walks/val/00824-Dd4bFSTQ8gi/ main.save_path=data/scene_graphs/00824-Dd4bFSTQ8gi
> /home/ncdev/miniforge3/envs/hovsg/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.26.0 is required for this version of SciPy (detected version 1.26.4
>   warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
> [2024-07-23 12:37:18,487][root][INFO] - Loaded ViT-H-14 model config.
> [2024-07-23 12:37:26,890][root][INFO] - Loading pretrained ViT-H-14 weights (checkpoints/laion2b_s32b_b79k.bin).
> Creating RGB-D point cloud: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226/226 [00:26<00:00,  8.58it/s]
> Extracting features: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226/226 [20:37<00:00,  5.47s/it]
> Merging 3d masks sequentially
>   6%|██████████                                                                                                                                                        | 14/225 [25:23<19:20:49, 330.09s/it][1]    100314 killed     python application/create_graph.py main.dataset=hm3dsem  
> ```
> 
> Traces show that some processes were killed on my machine, due to `Out of memory` problem. Despite the machine having 62 gigs of RAM. ![image (5)](https://private-user-images.githubusercontent.com/1905324/351365925-8128f88e-0840-44bb-816d-c90493d0cb9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTY3NDcsIm5iZiI6MTcyMjIxNjQ0NywicGF0aCI6Ii8xOTA1MzI0LzM1MTM2NTkyNS04MTI4Zjg4ZS0wODQwLTQ0YmItODE2ZC1jOTA0OTNkMGNiOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDEyNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTgzYWM1YWNjMWMyMTE2MGRjN2QzMzU4MTE2NWE4YWQ3NTQ2MWI1NTU1MjA0NWEzOTgwNWU5ODEyMGRlOGZmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NUFusfxIcXDYPsZ-DTksNq9jbTTqI8w1RrLvRSZzNr4)
> 
> What are the memory requirements for this script to run properly?
> 
> _Originally posted by @ADetilie in [#6 (comment)](https://github.com/hovsg/HOV-SG/issues/6#issuecomment-2245406682)_

Hi! I encountered the same issue with the process being killed during the merging of 3D masks. Will reinstalling Matplotlib solve this problem? Additionally, could you let me know which tool you used for tracing the executable? Was it perf?

**Comment by ADetilie** [comment]
@Eku127 most likely, what you see is an "Out of Memory" problem. 
You can "fix" it by changing "merge_type" to "hierarchical" in the config.
See this comment from the contributor: https://github.com/hovsg/HOV-SG/issues/8#issuecomment-2245998176

Reinstalling matplotlib won't help with this particular problem. It fixes yet another bug in the system. So, no need for matplotlib reinstallation until you encounter "AttributeError: module 'matplotlib.cbook' has no attribute '_Stack'" exception.

**Comment by Eku127** [comment]
> @Eku127, what you are seeing is most likely an "Out of Memory" problem. You can use workaround by changing "merge_type" to "hierarchical" in the config. See this comment from the contributor for more details: [#8 (comment)](https://github.com/hovsg/HOV-SG/issues/8#issuecomment-2245998176). -> This workaround worked for me... but I have 128 gig of RAM on my machine AND **turned off `oomd` service**
> 
> Reinstalling matplotlib won't help with this particular problem. It fixes a different bug in the system. So, there's no need to reinstall matplotlib unless you encounter the "AttributeError: module 'matplotlib.cbook' has no attribute '_Stack'" exception.

Got it. All I need is more RAM :rofl: 

However, I think there's still a lot of work needed to optimize RAM usage.

**Comment by abwerby** [comment]
I pushed a fix for the sequential merge high RAM usage, it is still slow, and we are working on improving it.
